### ISSUE TITLE
Captcha Issue

### ISSUE THREAD

**Issue by kavin-90** [Vladimir37/Hanako#1]
Hey Vladimir,

I installed Hanako but can't access Admin panel because of Captcha. 
Captcha shows up but it's font is too large that no letter/word is formed.
How to sort out this issue? OR How to disable captcha system for Admin
Screenshot http://s10.postimg.org/vkzqcervt/2016_02_16_001101.jpg

**Comment by Vladimir37** [comment]
Please look here: http://146.185.185.48:8080/admin/login You can see Captcha there?

**Comment by kavin-90** [comment]
Yes, your captcha is working but my capatcha does not show number so can you please tell me how to disable captcha or fix captcha?

**Comment by Vladimir37** [comment]
Unfortunately, now this is not possibly, but I add this possibility a little bit later. You have installed the latest version PangoCairo and ImageMagick?

**Comment by kavin-90** [comment]
Re-installed Imagemagick and now captcha works. 
But login is picking user/pass = Admin/Pass . It kept saying Incorrent user/pass.

**Comment by Vladimir37** [comment]
You changed `cofigs/db.json` or `configs/crypt_admin.json`? Try download original `app/db_storage/hanako_db.sqlite` and replace tour current `app/db_storage/hanako_db.sqlite`.

**Comment by Vladimir37** [comment]
Default sqlite contains Admin/Pass.
